### PR TITLE
Upgrade Quarkus and Helm extension versions

### PR DESCRIPTION
**Pull request by aureamunoz**

### CODE REVIEW

**Review by cmoulliard — COMMENTED** [review]
LGTM. I did a test locally successfully :-)

**Comment by aureamunoz** [comment]
The problem were the java version. Now the build passes, but we have a problem with the `helm`part.
I tried locally and for me, it's working. Could you please take a look @cmoulliard ?

**Comment by cmoulliard** [comment]
> Now the build passes, but we have a problem with the `helm`part.

???

**Comment by cmoulliard** [comment]
> Something went wrong

This is because the folder's name of the helm chart changed from ./target/helm/kubernetes/atomic-fruits` to `atomic-fruits-service`. You can check locally

**Comment by cmoulliard** [comment]
If I execute locally the same commands of the PR workflow, pod is well created except that I got this datasource issue
```
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Unable to find datasource '<default>' for persistence unit '<default>': Datasource '<default>' is not configured. │
│     at io.quarkus.hibernate.orm.runtime.PersistenceUnitUtil.unableToFindDataSource(PersistenceUnitUtil.java:112)                                                                      │
│     at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.injectDataSource(FastBootHibernatePersistenceProvider.java:397)                                          │
│     at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.buildRuntimeSettings(FastBootHibernatePersistenceProvider.java:212)                                      │
│     at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.getEntityManagerFactoryBuilderOrNull(FastBootHibernatePersistenceProvider.java:183)                      │
│     at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:66)                                 │
│     at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)                                                                                                │
│     at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)                                                                                                │
│     at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:157)                                                                                         │
│     at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:64)                                                                                                            │
│     at java.base/java.lang.Thread.run(Thread.java:840)                                                                                                                                │
│ Caused by: io.quarkus.runtime.configuration.ConfigurationException: Datasource '<default>' is not configured. To solve this, configure datasource '<default>'. Refer to https://quark │
```

**Pull request merged**
